version: '2'
services:
  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_VHOST=/
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
    restart: always
    ports:
      - 15672:15672
      - 4369:4369
      - 5672:5672
      - 25672:25672


  #访问此rabbitmq主页时会出现无法访问，这是因为没有开启插件；
  #开启插件：首先使用命令进入容器  docker exec -it rabbit /bin/bash
  #开启插件命令：rabbitmq-plugins enable rabbitmq_management