version: '2'
services:
  sdk-mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;' --innodb-flush-log-at-trx-commit=0
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /data/docker/mysql/lib:/var/lib/mysql
#      - /home/workspace/mobikok-op/docker/my.conf:/etc/mysql/my.conf
#      - /home/workspace/mobikok-op/docker/mysql.cnf:/etc/mysql/mysql.conf.d/mysql.cnf
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=mobikok@2020
    networks:
      - mobikok

  sdk-redis:
    image: redis:4.0.13
    restart: always
    command: redis-server --requirepass mobikok@2020
    ports:
      - 6379:6379
    volumes:
      - /data/docker/data/redis:/data
#      - /home/workspace/mobikok-op/docker/redis.conf:/usr/local/etc/redis/redis.conf
#      - /home/workspace/mobikok-op/docker/redis.conf:/etc/redis/redis.conf
    environment:
      - TZ=Asia/Shanghai
    networks:
      - mobikok

networks:
  mobikok:
    driver: bridge
