server:
  port: 2323
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://218.17.186.161:3306/kok_ssp?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    #    url:  jdbc:mysql://54.210.217.196:3306/sloth_coupons?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://218.17.186.161:3305/mashup?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    #    password: "@dfei$@DCcsYG"
    password: "sloth"
    #    password: "123456"
    initialSize: 1
    minIdle: 1
    maxIdle: 5
    maxActive: 50
    maxWait: 10000
    timeBetweenEvictionRunsMillis: 10000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    filters: stat
  redis:
    host: 120.79.30.86
    port: 6379
    password: 123456
  # 上传文件总的最大值
  # 单个文件的最大值
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 500MB
security:
  oauth2:
    resource:
      id: resource
      user-info-uri: http://127.0.0.1:2121/user
      prefer-token-info: false